'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const code=fs.readFileSync(path.resolve(__dirname,'../../gifted_entry.js'),'utf8');
function setup(enabled=true){const values=new Map(),elements=[],listeners=[];const storage={get length(){return values.size;},key:i=>[...values.keys()][i],removeItem:k=>values.delete(k)};
const document={body:{append:e=>elements.push(e),classList:{add(){},remove(){}}},createElement:tag=>({tag,contentWindow:{},setAttribute(){},focus(){},children:[],append(...items){this.children.push(...items);},remove(){const i=elements.indexOf(this);if(i>=0)elements.splice(i,1);}})};
let resolveFetch;const context={URL,URLSearchParams,AbortSignal,location:{href:'https://school.example/ebook/?gifted=plan-1&segment=week-1',search:'?gifted=plan-1&segment=week-1'},localStorage:storage,document,GIFTED_HOMEWORK_RELEASE:{enabled,studentApi:'https://api.example/student'},fetch:()=>new Promise(r=>{resolveFetch=r;})};context.window=context;
vm.createContext(context);vm.runInContext(code,context);
const auth={currentUser:{uid:'student-a',getIdToken:async()=> 'opaque'},onAuthStateChanged(fn){listeners.push(fn);return()=>{};}};
const ready=extra=>context.GiftedEbook.ready({auth,result:{studentName:'合成學生'},mode:'remembered_session',...extra});
return {ui:context.GiftedEbook,ready,auth,values,elements,listeners,resolveFetch:()=>resolveFetch({ok:true,json:async()=>({privateResult:'owner-only'})})};}
test('closed config and teacher preview never create a student frame',()=>{for(const extra of [{preview:true},{mode:'god_session'},{mode:'student_preview'},{result:{isAdmin:true} }]){const f=setup();f.ready(extra);assert.equal(f.elements.length,0);}const f=setup(false);f.ready();assert.equal(f.elements.length,0);});
test('return then logout erases only current owner drafts; a different login cannot reuse the bridge',()=>{const f=setup();f.ready();f.values.set('gifted-answer-outbox-v1:student-a|p','old');f.values.set('gifted-correction-request:student-a:p','private');f.values.set('unrelated','retain');assert.throws(()=>f.ui.getTransport({}),/LOGIN_REQUIRED/);f.ui.close(false);assert.equal(f.values.size,3);f.ui.close(true);assert.deepEqual([...f.values.keys()],['unrelated']);f.ready();f.auth.currentUser={uid:'student-b',getIdToken:async()=> 'new'};assert.throws(()=>f.ui.getTransport({}),/LOGIN_REQUIRED/);});
test('logout invalidates a request in flight and removes the frame before any stale response is returned',async()=>{const f=setup();f.ready();const frame=f.elements[0].children[1],transport=f.ui.getTransport(frame.contentWindow);const pending=transport.request({action:'task'});await new Promise(setImmediate);f.ui.close(true);f.resolveFetch();await assert.rejects(pending,/LOGIN_REQUIRED/);assert.equal(f.elements.length,0);assert.throws(()=>f.ui.getTransport(frame.contentWindow),/LOGIN_REQUIRED/);});
