async page => {
 const checks=[]; const check=(v,label)=>{if(!v)throw new Error(label);checks.push(label);};
 const base='http://127.0.0.1:8897/ebook/tests/report_late_fixture.html';
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.waitForFunction(()=>window.__fixture?.ready);
 const card=page.locator('article').first();
 check(await card.getByRole('button',{name:'補交分數',exact:true}).count()===1,'overdue form stays open');
 check(await page.locator('article').nth(1).getByText('準時回報',{exact:true}).count()===1,'on-time label');
 check(await page.locator('article').nth(2).getByText('遲交',{exact:true}).count()===1,'corrected Sheet score retains late badge');
 check(await page.locator('article').nth(4).locator('.rp-timing').count()===0,'legacy not classified');
 check(await page.locator('article').nth(6).getByRole('button',{name:'送出分數',exact:true}).count()===1,'no deadline normal form');
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'student mobile no overflow');
 await page.screenshot({path:'output/playwright/late-student-mobile.png',fullPage:true});
 await card.locator('input').fill('85');await card.getByRole('button',{name:'補交分數',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('rp-message').textContent.includes('已收到補交'));
 check(await card.getByText('遲交',{exact:true}).count()===1,'durable acknowledgement shows late');
 await page.evaluate(()=>window.__fixture.complete());await page.getByRole('button',{name:'重新整理',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('article').textContent.includes('成績登記完成'));
 check(await card.getByText('遲交',{exact:true}).count()===1,'completion retains late receipt');
 await page.goto(base+'?crossing=2500&clockSkew=86400000');await page.waitForFunction(()=>window.__fixture?.ready);
 await page.locator('article input').fill('92');await page.locator('article summary').click();
 check(await page.getByRole('button',{name:'送出分數',exact:true}).count()===1,'server clock before deadline');
 await page.getByRole('button',{name:'補交分數',exact:true}).waitFor();
 check(await page.locator('article input').inputValue()==='92','crossing keeps input');
 check(await page.locator('details').getAttribute('open')!==null,'crossing keeps answer open');
 check(await page.evaluate(()=>window.__fixture.calls.filter(x=>x.data.action==='list').length)===1,'deadline timer adds no network request');
 await page.evaluate(()=>window.__fixture.mode='lost');await page.getByRole('button',{name:'補交分數',exact:true}).click();
 await page.getByRole('button',{name:'再次確認送出',exact:true}).waitFor();
 check(await page.locator('article input').inputValue()==='92','transport failure keeps draft');
 await page.getByRole('button',{name:'再次確認送出',exact:true}).click();await page.waitForFunction(()=>document.getElementById('rp-message').textContent.includes('已收到補交'));
 await page.goto(base+'?admin=1');await page.waitForFunction(()=>window.__fixture?.ready);
 await page.getByRole('button',{name:'回報與同步紀錄',exact:true}).click();await page.locator('table').waitFor();
 const text=await page.locator('table').innerText();for(const word of ['準時回報','遲交','未回報','舊紀錄未記錄期限','已登記（無回報紀錄）','當時期限'])check(text.includes(word),'teacher '+word);
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'teacher mobile contained table');
 await page.screenshot({path:'output/playwright/late-admin-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'編輯附件／答案',exact:true}).click();await page.locator('#rpa-form').waitFor();
 check((await page.locator('#rpa-form').innerText()).includes('逾期仍可補交'),'editor explains soft deadline');
 await page.setViewportSize({width:1280,height:900});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'teacher desktop no overflow');
 await page.screenshot({path:'output/playwright/late-admin-desktop.png',fullPage:true});
 check(errors.length===0,'no page errors');return{passed:checks.length,checks,errors};
}
